apiVersion: v1
kind: Pod
metadata:
        labels:
                run: michelle
        name: michelle
        namespace: default
spec:
        containers:
                - image: nginx
                  name: nginx
